"""Utilities for working with Clingo."""

import argparse
import logging
from importlib.resources import path
from typing import List, Sequence, Tuple

from clingo import Control, Symbol, SymbolType

from asplain.llm.utils.graph import Graph
from asplain.utils.logging import colored

log = logging.getLogger(__name__)


def symbols_to_prg(symbols: List[Symbol]) -> str:
    """Converts a list of symbols to a program string."""
    return "\n".join(str(s) + "." for s in symbols)


def divide_space_string(space_string: str) -> tuple[list[str], list[str]]:
    """
    Divide the string into atoms to include and exclude
    """
    include = [atom for atom in space_string.split() if not atom.startswith("-")]
    exclude = [atom[1:] for atom in space_string.split() if atom.startswith("-")]
    return include, exclude


def assumptions_as_ic(assumptions: Sequence[Tuple[str, bool]]) -> str:
    """
    Convert assumptions to integrity constraints.

    Args:
        assumptions: List of assumptions as tuples of (Symbol, bool).

    Returns:
        A string representing the integrity constraints.
    """
    prg = ""
    for s, b in assumptions:
        if b:
            prg += f"% @assume(true)\n:- not {s}.\n"
        else:
            prg += f"% @assume(false)\n:- {s}.\n"
    return prg


def parse_constants(arguments: list[str]) -> dict[str, str]:
    """
    Parse constants from the command line arguments.
    We need these constrants in both steps and since we can't fork the control object,
    we parse them here.

    Args:
        arguments (list): The command line arguments.
    Returns:
        list: A list of constants in the form <id>=<term>.
    """
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument(
        "-c",
        "--const",
        action="append",
        help="Replace term occurrences of <id> with <term> (must have form <id>=<term>)",
        type=lambda s: s if "=" in s else parser.error("Constants must have form <id>=<term>"),
    )
    args, _ = parser.parse_known_args(arguments)
    input_consts = {c.split("=")[0]: c.split("=")[1] for c in args.const} if args.const else {}
    return input_consts


def constants_to_args(constants: dict[str, str]) -> list[str]:
    """
    Convert constants dictionary to command line arguments.

    Args:
        constants: A dictionary of constants.

    Returns:
        A list of command line arguments representing the constants.
    """
    args = []
    for k, v in constants.items():
        args.append(f"-c {k}={v}")
    return args


def load_encoding(ctl: Control, encoding_name: str) -> None:
    """
    Load an encoding into the given clingo Control object.
    """
    with path("asplain.encodings", encoding_name) as base_encoding:
        log.debug("Loading encoding: %s", base_encoding)
        ctl.load(str(base_encoding))


def assert_no_errors(symbols: List[Symbol], function_name: str = "error") -> None:
    """
    Check for error symbols in the given list of symbols.
    If any error symbols are found, raise a RuntimeError with the error messages.

    Args:
        symbols: A list of clingo.Symbol objects to check for errors.

    Raises:
        RuntimeError: If any error symbols are found.
    """
    error_messages = [str(s) for s in symbols if s.name == function_name]
    if error_messages:
        m = "Errors generated by the encoding:\n" + "\n".join(error_messages)
        log.error(m)
        raise RuntimeError(m)


def model_symbols(model_pg_symbols: Sequence[Symbol], graph_name: str = "ref") -> List[Symbol]:
    """
    Extract model symbols from the program graph string.
    Placeholder implementation.
    """
    model = []
    shown = []
    for s in model_pg_symbols:
        is_model_node = (
            s.match("model", 2) and s.arguments[1].match(graph_name, 0) and s.arguments[0].type == SymbolType.Function
        )
        if is_model_node:
            model.append(s.arguments[0])
            continue
        is_show_tag = s.match("tag", 2) and s.arguments[1].match("shown", 0)
        if is_show_tag:
            shown.append(s.arguments[0])

    model = [s for s in model if s in shown]
    return model


def print_foil(foil_pg: str) -> None:
    ctl = Control()
    ctl.add("base", [], foil_pg)
    ctl.ground([("base", [])])
    with ctl.solve(yield_=True) as handle:
        model = handle.model()
        graph = Graph("".join([str(s) + "." for s in model.symbols(shown=True)]))
        added_rules = []
        removed_rules = []
        foil_atoms = []
        for node in graph._nodes.values():
            if node.type == "atom" and "foil" in node.models:
                foil_atoms.append(node.id)
            if node.programs == set(["ref"]):
                added_rules.append(node.tags["first_order"])
            if node.programs == set(["foil"]):
                removed_rules.append(node.tags["first_order"])

        print(colored("blue", "Foil model: " + " ".join([str(s) for s in foil_atoms])))
        if len(removed_rules) > 0:
            print(colored("red", "            Removed: " + "\t".join([str(s) for s in removed_rules])))
        if len(added_rules) > 0:
            print(colored("green", "            Added: " + "\t".join([str(s) for s in added_rules])))


def get_query_prg(query_include: List[Symbol], query_exclude: List[Symbol]) -> str:
    qi = "".join([f"query({str(s)},1)." for s in query_include])
    qe = "".join([f"query({str(s)},0)." for s in query_exclude])
    return qi + qe
